version: "3.8"
services:
  service-config:
    build: ./service-config
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=service-config
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/Noubissie237/banking-system-cloud-conf
    networks:
      - microservices-network
        #8081 c'est la port pour acceder au service depuis l'exterieur or 8761 interne c' le port ou l'app va tourner

  service-registry:
    build: ./service-registry
    depends_on:
      - service-config
    environment:
      - SPRING_APPLICATION_NAME=service-registry
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8080
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8080
    ports:
      - "8081:8761"
    networks:
      - microservices-network

  service-users:
    build: ./service-users
    depends_on:
      - service-config
      - service-registry
    environment:
      - SPRING_APPLICATION_NAME=service-users
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8080
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8080
    ports:
      - "8083" #port interne car docker se charge d'allouer un port dynamquement aux instances lanc
    networks:
      - microservices-network

  service-proxy:
    build: ./service-proxy
    depends_on:
      - service-config
      - service-registry
    environment:
      - SPRING_APPLICATION_NAME=service-proxy
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8080
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8080
    ports:
      - "8082:8079"
    networks:
      - microservices-network
  
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  #port pour rabbitmq envoy les requet
      - "15672:15672" #port pour l'interface de gestion user
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge  
  