services:
  # Service de configuration
  service-config:
    build: ./service-config
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=service-config
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/Noubissie237/banking-system-cloud-conf
    networks:
      - banking-system-network

  # Service d'enrégistrement
  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=service-registry
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8080
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8080
    networks:
      - banking-system-network
    depends_on:
      - service-config

  # Service proxy
  service-proxy:
    build: ./service-proxy
    ports:
      - "8079:8079"
    environment:
      - SPRING_APPLICATION_NAME=service-proxy
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8080
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8080
    networks:
      - banking-system-network
    depends_on:
      - service-config
      - service-registry


networks:
  banking-system-network:
    driver: bridge

  