# service authentification
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-authentification-hpa
  namespace: banking-system-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-authentification
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
---
# service users
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-users-hpa
  namespace: banking-system-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-users
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
---
# service account-management
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-account-management-hpa
  namespace: banking-system-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-account-management
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
---
# service depot
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-depot-hpa
  namespace: banking-system-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-depot
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
---
# service retrait
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-retrait-hpa
  namespace: banking-system-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-retrait
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
---
# service tranfert
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-tranfert-hpa
  namespace: banking-system-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-tranfert
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
---
# service transactions
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-transactions-hpa
  namespace: banking-system-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-transactions
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20