apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: banking-system-app
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3306
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: banking-system-app
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5673
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15673
      targetPort: 15672
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: eventstore-service
  namespace: banking-system-app
spec:
  selector:
    app: eventstoredb
  ports:
    - protocol: TCP
      port: 2114
      targetPort: 2113
  type: LoadBalancer
---
# Exposition du service config
apiVersion: v1
kind: Service
metadata:
  name: service-config
  namespace: banking-system-app
spec:
  type: LoadBalancer
  selector:
    app: service-config
  ports:
    - port: 2370       
      targetPort: 2370 
---
# Exposition du service registry
apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: banking-system-app
spec:
  selector:
    app: service-registry
  type: LoadBalancer
  ports:
    - port: 8761
      targetPort: 8761
---
# Exposition du service proxy
apiVersion: v1
kind: Service
metadata:
  name: service-proxy
  namespace: banking-system-app
spec:
  selector:
    app: service-proxy
  type: LoadBalancer
  ports:
    - port: 8079
      targetPort: 8079
---
# Exposition du service d'authentification
apiVersion: v1
kind: Service
metadata:
  name: service-authentification
  namespace: banking-system-app
spec:
  selector:
    app: service-authentification
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
---
# Exposition du service de depot
apiVersion: v1
kind: Service
metadata:
  name: service-depot
  namespace: banking-system-app
spec:
  selector:
    app: service-depot
  type: LoadBalancer
  ports:
    - port: 8085
      targetPort: 8085
---
# Exposition du service de retrait
apiVersion: v1
kind: Service
metadata:
  name: service-retrait
  namespace: banking-system-app
spec:
  selector:
    app: service-retrait
  type: LoadBalancer
  ports:
    - port: 8086
      targetPort: 8086
---
# Exposition du service de transfert
apiVersion: v1
kind: Service
metadata:
  name: service-tranfert
  namespace: banking-system-app
spec:
  selector:
    app: service-tranfert
  type: LoadBalancer
  ports:
    - port: 8087
      targetPort: 8087
---
# Exposition du service de transactions
apiVersion: v1
kind: Service
metadata:
  name: service-transactions
  namespace: banking-system-app
spec:
  selector:
    app: service-transactions
  type: LoadBalancer
  ports:
    - port: 8088
      targetPort: 8088
---
# Exposition du service users
apiVersion: v1
kind: Service
metadata:
  name: service-users
  namespace: banking-system-app
spec:
  selector:
    app: service-users
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
---
# Exposition du service admin
apiVersion: v1
kind: Service
metadata:
  name: service-admin
  namespace: banking-system-app
spec:
  selector:
    app: service-admin
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: 8083
---
# Exposition du service account management
apiVersion: v1
kind: Service
metadata:
  name: service-account-management
  namespace: banking-system-app
spec:
  selector:
    app: service-account-management
  type: LoadBalancer
  ports:
    - port: 8084
      targetPort: 8084
---
# Exposition du service de notification
apiVersion: v1
kind: Service
metadata:
  name: service-notification
  namespace: banking-system-app
spec:
  selector:
    app: service-notification
  type: LoadBalancer
  ports:
    - port: 8089
      targetPort: 8089