name: Build et Push de la première couche

on:
  push:
    branches:
      - NK_Wilfried

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.MY_DOCKER_HUB_TOKEN }}

      # Service config
      - name: Build Docker image for service-config
        run: docker build -t noubissie237/service-config:latest ./service-config/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/service-config:latest

      # Service registry
      - name: Build Docker image for service-registry
        run: docker build -t noubissie237/service-registry:latest ./service-registry/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/service-registry:latest


      # Service proxy
      - name: Build Docker image for service-proxy
        run: docker build -t noubissie237/service-proxy:latest ./service-proxy/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/service-proxy:latest